name: CI
on: [push, pull_request]

jobs:
  build-windows-msys2-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git msys2-devel base-devel binutils mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-SDL2 mingw-w64-${{ matrix.arch }}-glew mingw-w64-${{ matrix.arch }}-pkg-config
          update: true
      - name: Add staging repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[staging]\nServer = https://repo.msys2.org/staging/\nSigLevel = Never\n|' /etc/pacman.conf
      - name: Update using staging
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse
      - name: CI-Build
        run: |
          cd "C:\_\.ci"
          SET MINGW_INSTALLS={{ matrix.msystem }}
          build_msys2.bat
        shell: cmd
        env:
          CC: gcc
          CXX: g++
# TODO(#20): no CI on macos
# TODO(#21): no CI on freebsd
