name: CI
on: [push, pull_request]

jobs:
  build-windows-msys2-mingw64:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 }
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: mingw-w64-${{ matrix.arch }}-SDL2 mingw-w64-${{ matrix.arch }}-glew mingw-w64-${{ matrix.arch }}-pkg-config
          update: true
      - name: Update
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse
      - name: CI-Build
        run: |
          cd "C:\_"
          build_msys2.bat
          SET MINGW_INSTALLS=${{ matrix.msystem }}
          build_msys2.bat
        shell: cmd
        env:
          CC: gcc
          CXX: g++
# TODO(#20): no CI on macos
# TODO(#21): no CI on freebsd
